### PR TITLE
Simplify defaults() function using Object.assign

### PR DESCRIPTION
**Pull request by samosad**

### CODE REVIEW

**Comment by samosad** [comment]
done. but can't figure out why rollup bundler doesn't include imported module in resulting file =(

**Comment by STAH** [comment]
I realized that native Object.assign don't have the same behaviour that ''defaults()":

```javascript
var settings = { test1: 1, test2: 2 };
var opts1 = { test1: 3, test2: null };
var opts2 = { test1: 3, test2: null };

// overrides from settings only if property is undefined or null
defaults(opts1, settings);
// >> Object {test1: 3, test2: 2}

// overrides _all_ properties from settings
Object.assign(opts2, settings);
// >> Object {test1: 1, test2: 2}
```

**Comment by STAH** [comment]
Ok, I've created "object-assign" branch: could you take a look on it and if it's ok i'll merge it.

**Comment by samosad** [comment]
Hi, as I can see - everything's fine. Your example above was not correct because Obj.assign takes agrs in different order - target first and sourse/s - second. In new branch you did it right. I did'n found any info 'bout rollup plugins, so thanks for help with config

**Comment by STAH** [comment]
You're right, thanks.

**Pull request closed without merging**
